name: 'Install powershell'
description: 'Install powershell'
inputs:
  sudo:
    description: "Set to false to disable sudo"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/install.sh
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
